/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ykqapvhxxyuozzmpalyi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrcWFwdmh4eHl1b3p6bXBhbHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1NTg2MjYsImV4cCI6MjA4MDEzNDYyNn0.xPWls-jeUBiARVVWFoQqVwokpEeWU8ZcqSYpoia-j48"